// [country_code, lat, lng, name_en, name_zh]
export type CountryCentroid = {
  code: string; lat: number; lng: number; en: string; zh: string;
};

export const COUNTRY_CENTROIDS: CountryCentroid[] = [
  // Americas
  { code: "US", lat: 39.5,  lng: -98.5,  en: "USA",         zh: "美国" },
  { code: "CA", lat: 56.1,  lng: -106.3, en: "Canada",      zh: "加拿大" },
  { code: "MX", lat: 23.6,  lng: -102.5, en: "Mexico",      zh: "墨西哥" },
  { code: "BR", lat: -14.2, lng: -51.9,  en: "Brazil",      zh: "巴西" },
  { code: "AR", lat: -38.4, lng: -63.6,  en: "Argentina",   zh: "阿根廷" },
  { code: "CO", lat: 4.6,   lng: -74.1,  en: "Colombia",    zh: "哥伦比亚" },
  { code: "EC", lat: -1.8,  lng: -78.2,  en: "Ecuador",     zh: "厄瓜多尔" },
  { code: "UY", lat: -32.5, lng: -55.8,  en: "Uruguay",     zh: "乌拉圭" },
  { code: "CL", lat: -35.7, lng: -71.5,  en: "Chile",       zh: "智利" },
  { code: "PE", lat: -9.2,  lng: -75.0,  en: "Peru",        zh: "秘鲁" },
  { code: "VE", lat: 6.4,   lng: -66.6,  en: "Venezuela",   zh: "委内瑞拉" },
  { code: "CR", lat: 9.9,   lng: -84.1,  en: "Costa Rica",  zh: "哥斯达黎加" },
  { code: "PA", lat: 8.5,   lng: -80.8,  en: "Panama",      zh: "巴拿马" },
  { code: "GT", lat: 15.8,  lng: -90.2,  en: "Guatemala",   zh: "危地马拉" },
  { code: "JM", lat: 18.1,  lng: -77.3,  en: "Jamaica",     zh: "牙买加" },
  { code: "CU", lat: 21.5,  lng: -79.5,  en: "Cuba",        zh: "古巴" },
  { code: "BO", lat: -16.3, lng: -63.6,  en: "Bolivia",     zh: "玻利维亚" },
  { code: "PY", lat: -23.4, lng: -58.4,  en: "Paraguay",    zh: "巴拉圭" },
  // Europe
  { code: "GB", lat: 54.4,  lng: -3.4,   en: "England",     zh: "英格兰" },
  { code: "DE", lat: 51.2,  lng: 10.5,   en: "Germany",     zh: "德国" },
  { code: "FR", lat: 46.2,  lng: 2.2,    en: "France",      zh: "法国" },
  { code: "ES", lat: 40.5,  lng: -3.7,   en: "Spain",       zh: "西班牙" },
  { code: "IT", lat: 41.9,  lng: 12.6,   en: "Italy",       zh: "意大利" },
  { code: "PT", lat: 39.4,  lng: -8.2,   en: "Portugal",    zh: "葡萄牙" },
  { code: "NL", lat: 52.1,  lng: 5.3,    en: "Netherlands", zh: "荷兰" },
  { code: "BE", lat: 50.5,  lng: 4.5,    en: "Belgium",     zh: "比利时" },
  { code: "PL", lat: 51.9,  lng: 19.1,   en: "Poland",      zh: "波兰" },
  { code: "HR", lat: 45.1,  lng: 15.2,   en: "Croatia",     zh: "克罗地亚" },
  { code: "RS", lat: 44.0,  lng: 21.0,   en: "Serbia",      zh: "塞尔维亚" },
  { code: "CH", lat: 46.8,  lng: 8.2,    en: "Switzerland", zh: "瑞士" },
  { code: "AT", lat: 47.5,  lng: 14.5,   en: "Austria",     zh: "奥地利" },
  { code: "SE", lat: 60.1,  lng: 18.6,   en: "Sweden",      zh: "瑞典" },
  { code: "DK", lat: 56.3,  lng: 9.5,    en: "Denmark",     zh: "丹麦" },
  { code: "NO", lat: 60.5,  lng: 8.5,    en: "Norway",      zh: "挪威" },
  { code: "TR", lat: 38.9,  lng: 35.2,   en: "Türkiye",     zh: "土耳其" },
  { code: "RO", lat: 45.9,  lng: 24.9,   en: "Romania",     zh: "罗马尼亚" },
  { code: "UA", lat: 48.4,  lng: 31.2,   en: "Ukraine",     zh: "乌克兰" },
  { code: "GR", lat: 39.1,  lng: 21.8,   en: "Greece",      zh: "希腊" },
  { code: "HU", lat: 47.2,  lng: 19.5,   en: "Hungary",     zh: "匈牙利" },
  { code: "CZ", lat: 49.8,  lng: 15.5,   en: "Czech Rep.",  zh: "捷克" },
  { code: "SK", lat: 48.7,  lng: 19.7,   en: "Slovakia",    zh: "斯洛伐克" },
  { code: "AL", lat: 41.2,  lng: 20.2,   en: "Albania",     zh: "阿尔巴尼亚" },
  { code: "SI", lat: 46.1,  lng: 14.9,   en: "Slovenia",    zh: "斯洛文尼亚" },
  { code: "RU", lat: 61.5,  lng: 105.3,  en: "Russia",      zh: "俄罗斯" },
  { code: "FI", lat: 61.9,  lng: 25.7,   en: "Finland",     zh: "芬兰" },
  // Africa
  { code: "MA", lat: 31.8,  lng: -7.1,   en: "Morocco",     zh: "摩洛哥" },
  { code: "EG", lat: 26.8,  lng: 30.8,   en: "Egypt",       zh: "埃及" },
  { code: "NG", lat: 9.1,   lng: 8.7,    en: "Nigeria",     zh: "尼日利亚" },
  { code: "SN", lat: 14.5,  lng: -14.5,  en: "Senegal",     zh: "塞内加尔" },
  { code: "GH", lat: 7.9,   lng: -1.0,   en: "Ghana",       zh: "加纳" },
  { code: "CM", lat: 3.8,   lng: 11.5,   en: "Cameroon",    zh: "喀麦隆" },
  { code: "CI", lat: 7.5,   lng: -5.5,   en: "Côte d'Ivoire", zh: "科特迪瓦" },
  { code: "ZA", lat: -28.5, lng: 24.7,   en: "South Africa",zh: "南非" },
  { code: "TN", lat: 33.9,  lng: 9.5,    en: "Tunisia",     zh: "突尼斯" },
  { code: "KE", lat: -0.0,  lng: 37.9,   en: "Kenya",       zh: "肯尼亚" },
  { code: "ET", lat: 9.1,   lng: 40.5,   en: "Ethiopia",    zh: "埃塞俄比亚" },
  { code: "DZ", lat: 28.0,  lng: 1.7,    en: "Algeria",     zh: "阿尔及利亚" },
  { code: "TZ", lat: -6.4,  lng: 35.0,   en: "Tanzania",    zh: "坦桑尼亚" },
  // Asia
  { code: "CN", lat: 35.9,  lng: 104.2,  en: "China",       zh: "中国" },
  { code: "JP", lat: 36.2,  lng: 138.3,  en: "Japan",       zh: "日本" },
  { code: "KR", lat: 35.9,  lng: 127.8,  en: "South Korea", zh: "韩国" },
  { code: "IN", lat: 20.6,  lng: 79.0,   en: "India",       zh: "印度" },
  { code: "SA", lat: 23.9,  lng: 45.1,   en: "Saudi Arabia",zh: "沙特阿拉伯" },
  { code: "IR", lat: 32.4,  lng: 53.7,   en: "Iran",        zh: "伊朗" },
  { code: "QA", lat: 25.4,  lng: 51.2,   en: "Qatar",       zh: "卡塔尔" },
  { code: "AE", lat: 23.4,  lng: 53.8,   en: "UAE",         zh: "阿联酋" },
  { code: "IQ", lat: 33.2,  lng: 43.7,   en: "Iraq",        zh: "伊拉克" },
  { code: "ID", lat: -0.8,  lng: 113.9,  en: "Indonesia",   zh: "印度尼西亚" },
  { code: "MY", lat: 3.8,   lng: 109.7,  en: "Malaysia",    zh: "马来西亚" },
  { code: "TH", lat: 15.9,  lng: 100.9,  en: "Thailand",    zh: "泰国" },
  { code: "VN", lat: 14.1,  lng: 108.3,  en: "Vietnam",     zh: "越南" },
  { code: "PH", lat: 12.9,  lng: 121.8,  en: "Philippines", zh: "菲律宾" },
  { code: "PK", lat: 30.4,  lng: 69.3,   en: "Pakistan",    zh: "巴基斯坦" },
  { code: "BD", lat: 23.7,  lng: 90.4,   en: "Bangladesh",  zh: "孟加拉国" },
  { code: "UZ", lat: 41.4,  lng: 64.6,   en: "Uzbekistan",  zh: "乌兹别克斯坦" },
  // Oceania
  { code: "AU", lat: -25.3, lng: 133.8,  en: "Australia",   zh: "澳大利亚" },
  { code: "NZ", lat: -40.9, lng: 174.9,  en: "New Zealand", zh: "新西兰" },
];
