// Team name → ISO country code mapping for flagcdn.com
const TEAM_FLAG_CODES: Record<string, string> = {
  // Group A: Mexico, South Korea, Czechia, South Africa
  "Mexico": "mx",
  "South Korea": "kr",
  "Czechia": "cz",
  "South Africa": "za",
  // Group B: Canada, Bosnia & Herzegovina, Qatar, Switzerland
  "Canada": "ca",
  "Bosnia & Herzegovina": "ba",
  "Qatar": "qa",
  "Switzerland": "ch",
  // Group C: Brazil, Morocco, Haiti, Scotland
  "Brazil": "br",
  "Morocco": "ma",
  "Haiti": "ht",
  "Scotland": "gb-sct",
  // Group D: USA, Paraguay, Australia, Türkiye
  "USA": "us",
  "Paraguay": "py",
  "Australia": "au",
  "Türkiye": "tr",
  "Turkey": "tr",
  // Group E: Germany, Curaçao, Ivory Coast, Ecuador
  "Germany": "de",
  "Curaçao": "cw",
  "Curacao": "cw",
  "Ivory Coast": "ci",
  "Ecuador": "ec",
  // Group F: Netherlands, Japan, Sweden, Tunisia
  "Netherlands": "nl",
  "Japan": "jp",
  "Sweden": "se",
  "Tunisia": "tn",
  // Group G: Belgium, Egypt, Iran, New Zealand
  "Belgium": "be",
  "Egypt": "eg",
  "Iran": "ir",
  "New Zealand": "nz",
  // Group H: Spain, Cape Verde, Saudi Arabia, Uruguay
  "Spain": "es",
  "Cape Verde": "cv",
  "Saudi Arabia": "sa",
  "Uruguay": "uy",
  // Group I: France, Senegal, Iraq, Norway
  "France": "fr",
  "Senegal": "sn",
  "Iraq": "iq",
  "Norway": "no",
  // Group J: Argentina, Algeria, Austria, Jordan
  "Argentina": "ar",
  "Algeria": "dz",
  "Austria": "at",
  "Jordan": "jo",
  // Group K: Portugal, DR Congo, Uzbekistan, Colombia
  "Portugal": "pt",
  "DR Congo": "cd",
  "Uzbekistan": "uz",
  "Colombia": "co",
  // Group L: England, Croatia, Ghana, Panama
  "England": "gb-eng",
  "Croatia": "hr",
  "Ghana": "gh",
  "Panama": "pa",
  // Extra
  "Wales": "gb-wls",
  "Poland": "pl",
  "Serbia": "rs",
  "Denmark": "dk",
  "Italy": "it",
  "Nigeria": "ng",
  "Costa Rica": "cr",
  "Cameroon": "cm",
  "Ukraine": "ua",
  "Greece": "gr",
  "Chile": "cl",
  "Peru": "pe",
  "Bolivia": "bo",
  "Venezuela": "ve",
  "Jamaica": "jm",
  "Honduras": "hn",
  "El Salvador": "sv",
  "Mali": "ml",
  "Burkina Faso": "bf",
  "Syria": "sy",
  "UAE": "ae",
  "Oman": "om",
  "Bahrain": "bh",
  "Kuwait": "kw",
  "China": "cn",
  "India": "in",
  "Thailand": "th",
  "Vietnam": "vn",
  "Indonesia": "id",
  "Philippines": "ph",
  "Fiji": "fj",
};

// Team display names per locale (key = English name, value = localized name)
const TEAM_NAMES: Record<string, Record<string, string>> = {
  zh: {
    // Group A
    "Mexico": "墨西哥",
    "South Korea": "韩国",
    "Czechia": "捷克",
    "South Africa": "南非",
    // Group B
    "Canada": "加拿大",
    "Bosnia & Herzegovina": "波黑",
    "Qatar": "卡塔尔",
    "Switzerland": "瑞士",
    // Group C
    "Brazil": "巴西",
    "Morocco": "摩洛哥",
    "Haiti": "海地",
    "Scotland": "苏格兰",
    // Group D
    "USA": "美国",
    "Paraguay": "巴拉圭",
    "Australia": "澳大利亚",
    "Türkiye": "土耳其",
    "Turkey": "土耳其",
    // Group E
    "Germany": "德国",
    "Curaçao": "库拉索",
    "Curacao": "库拉索",
    "Ivory Coast": "科特迪瓦",
    "Ecuador": "厄瓜多尔",
    // Group F
    "Netherlands": "荷兰",
    "Japan": "日本",
    "Sweden": "瑞典",
    "Tunisia": "突尼斯",
    // Group G
    "Belgium": "比利时",
    "Egypt": "埃及",
    "Iran": "伊朗",
    "New Zealand": "新西兰",
    // Group H
    "Spain": "西班牙",
    "Cape Verde": "佛得角",
    "Saudi Arabia": "沙特阿拉伯",
    "Uruguay": "乌拉圭",
    // Group I
    "France": "法国",
    "Senegal": "塞内加尔",
    "Iraq": "伊拉克",
    "Norway": "挪威",
    // Group J
    "Argentina": "阿根廷",
    "Algeria": "阿尔及利亚",
    "Austria": "奥地利",
    "Jordan": "约旦",
    // Group K
    "Portugal": "葡萄牙",
    "DR Congo": "刚果（金）",
    "Uzbekistan": "乌兹别克斯坦",
    "Colombia": "哥伦比亚",
    // Group L
    "England": "英格兰",
    "Croatia": "克罗地亚",
    "Ghana": "加纳",
    "Panama": "巴拿马",
    // Extra
    "Wales": "威尔士",
    "Poland": "波兰",
    "Serbia": "塞尔维亚",
    "Denmark": "丹麦",
    "Italy": "意大利",
    "Nigeria": "尼日利亚",
    "Costa Rica": "哥斯达黎加",
    "Cameroon": "喀麦隆",
    "Ukraine": "乌克兰",
    "Greece": "希腊",
    "Chile": "智利",
    "Peru": "秘鲁",
    "Bolivia": "玻利维亚",
    "Venezuela": "委内瑞拉",
    "Jamaica": "牙买加",
    "Honduras": "洪都拉斯",
    "El Salvador": "萨尔瓦多",
    "Mali": "马里",
    "Burkina Faso": "布基纳法索",
    "Syria": "叙利亚",
    "UAE": "阿联酋",
    "Oman": "阿曼",
    "Bahrain": "巴林",
    "Kuwait": "科威特",
    "China": "中国",
    "India": "印度",
    "Thailand": "泰国",
    "Vietnam": "越南",
    "Indonesia": "印度尼西亚",
    "Philippines": "菲律宾",
    "Fiji": "斐济",
  },
  es: {
    // Group A
    "Mexico": "México",
    "South Korea": "Corea del Sur",
    "Czechia": "Chequia",
    "South Africa": "Sudáfrica",
    // Group B
    "Canada": "Canadá",
    "Bosnia & Herzegovina": "Bosnia y Herzegovina",
    "Qatar": "Catar",
    "Switzerland": "Suiza",
    // Group C
    "Brazil": "Brasil",
    "Morocco": "Marruecos",
    "Haiti": "Haití",
    "Scotland": "Escocia",
    // Group D
    "USA": "Estados Unidos",
    "Paraguay": "Paraguay",
    "Australia": "Australia",
    "Türkiye": "Turquía",
    "Turkey": "Turquía",
    // Group E
    "Germany": "Alemania",
    "Curaçao": "Curazao",
    "Curacao": "Curazao",
    "Ivory Coast": "Costa de Marfil",
    "Ecuador": "Ecuador",
    // Group F
    "Netherlands": "Países Bajos",
    "Japan": "Japón",
    "Sweden": "Suecia",
    "Tunisia": "Túnez",
    // Group G
    "Belgium": "Bélgica",
    "Egypt": "Egipto",
    "Iran": "Irán",
    "New Zealand": "Nueva Zelanda",
    // Group H
    "Spain": "España",
    "Cape Verde": "Cabo Verde",
    "Saudi Arabia": "Arabia Saudita",
    "Uruguay": "Uruguay",
    // Group I
    "France": "Francia",
    "Senegal": "Senegal",
    "Iraq": "Irak",
    "Norway": "Noruega",
    // Group J
    "Argentina": "Argentina",
    "Algeria": "Argelia",
    "Austria": "Austria",
    "Jordan": "Jordania",
    // Group K
    "Portugal": "Portugal",
    "DR Congo": "RD del Congo",
    "Uzbekistan": "Uzbekistán",
    "Colombia": "Colombia",
    // Group L
    "England": "Inglaterra",
    "Croatia": "Croacia",
    "Ghana": "Ghana",
    "Panama": "Panamá",
    // Extra
    "Wales": "Gales",
    "Poland": "Polonia",
    "Serbia": "Serbia",
    "Denmark": "Dinamarca",
    "Italy": "Italia",
    "Nigeria": "Nigeria",
    "Costa Rica": "Costa Rica",
    "Cameroon": "Camerún",
    "Ukraine": "Ucrania",
    "Greece": "Grecia",
    "Chile": "Chile",
    "Peru": "Perú",
    "Bolivia": "Bolivia",
    "Venezuela": "Venezuela",
    "Jamaica": "Jamaica",
    "Honduras": "Honduras",
    "El Salvador": "El Salvador",
    "Mali": "Malí",
    "Burkina Faso": "Burkina Faso",
    "Syria": "Siria",
    "UAE": "EAU",
    "Oman": "Omán",
    "Bahrain": "Baréin",
    "Kuwait": "Kuwait",
    "China": "China",
    "India": "India",
    "Thailand": "Tailandia",
    "Vietnam": "Vietnam",
    "Indonesia": "Indonesia",
    "Philippines": "Filipinas",
    "Fiji": "Fiyi",
  },
  fr: {
    // Group A
    "Mexico": "Mexique",
    "South Korea": "Corée du Sud",
    "Czechia": "Tchéquie",
    "South Africa": "Afrique du Sud",
    // Group B
    "Canada": "Canada",
    "Bosnia & Herzegovina": "Bosnie-Herzégovine",
    "Qatar": "Qatar",
    "Switzerland": "Suisse",
    // Group C
    "Brazil": "Brésil",
    "Morocco": "Maroc",
    "Haiti": "Haïti",
    "Scotland": "Écosse",
    // Group D
    "USA": "États-Unis",
    "Paraguay": "Paraguay",
    "Australia": "Australie",
    "Türkiye": "Turquie",
    "Turkey": "Turquie",
    // Group E
    "Germany": "Allemagne",
    "Curaçao": "Curaçao",
    "Curacao": "Curaçao",
    "Ivory Coast": "Côte d'Ivoire",
    "Ecuador": "Équateur",
    // Group F
    "Netherlands": "Pays-Bas",
    "Japan": "Japon",
    "Sweden": "Suède",
    "Tunisia": "Tunisie",
    // Group G
    "Belgium": "Belgique",
    "Egypt": "Égypte",
    "Iran": "Iran",
    "New Zealand": "Nouvelle-Zélande",
    // Group H
    "Spain": "Espagne",
    "Cape Verde": "Cap-Vert",
    "Saudi Arabia": "Arabie saoudite",
    "Uruguay": "Uruguay",
    // Group I
    "France": "France",
    "Senegal": "Sénégal",
    "Iraq": "Irak",
    "Norway": "Norvège",
    // Group J
    "Argentina": "Argentine",
    "Algeria": "Algérie",
    "Austria": "Autriche",
    "Jordan": "Jordanie",
    // Group K
    "Portugal": "Portugal",
    "DR Congo": "RD Congo",
    "Uzbekistan": "Ouzbékistan",
    "Colombia": "Colombie",
    // Group L
    "England": "Angleterre",
    "Croatia": "Croatie",
    "Ghana": "Ghana",
    "Panama": "Panama",
    // Extra
    "Wales": "Pays de Galles",
    "Poland": "Pologne",
    "Serbia": "Serbie",
    "Denmark": "Danemark",
    "Italy": "Italie",
    "Nigeria": "Nigéria",
    "Costa Rica": "Costa Rica",
    "Cameroon": "Cameroun",
    "Ukraine": "Ukraine",
    "Greece": "Grèce",
    "Chile": "Chili",
    "Peru": "Pérou",
    "Bolivia": "Bolivie",
    "Venezuela": "Venezuela",
    "Jamaica": "Jamaïque",
    "Honduras": "Honduras",
    "El Salvador": "Salvador",
    "Mali": "Mali",
    "Burkina Faso": "Burkina Faso",
    "Syria": "Syrie",
    "UAE": "Émirats arabes unis",
    "Oman": "Oman",
    "Bahrain": "Bahreïn",
    "Kuwait": "Koweït",
    "China": "Chine",
    "India": "Inde",
    "Thailand": "Thaïlande",
    "Vietnam": "Viêt Nam",
    "Indonesia": "Indonésie",
    "Philippines": "Philippines",
    "Fiji": "Fidji",
  },
  de: {
    // Group A
    "Mexico": "Mexiko",
    "South Korea": "Südkorea",
    "Czechia": "Tschechien",
    "South Africa": "Südafrika",
    // Group B
    "Canada": "Kanada",
    "Bosnia & Herzegovina": "Bosnien und Herzegowina",
    "Qatar": "Katar",
    "Switzerland": "Schweiz",
    // Group C
    "Brazil": "Brasilien",
    "Morocco": "Marokko",
    "Haiti": "Haiti",
    "Scotland": "Schottland",
    // Group D
    "USA": "USA",
    "Paraguay": "Paraguay",
    "Australia": "Australien",
    "Türkiye": "Türkei",
    "Turkey": "Türkei",
    // Group E
    "Germany": "Deutschland",
    "Curaçao": "Curaçao",
    "Curacao": "Curaçao",
    "Ivory Coast": "Elfenbeinküste",
    "Ecuador": "Ecuador",
    // Group F
    "Netherlands": "Niederlande",
    "Japan": "Japan",
    "Sweden": "Schweden",
    "Tunisia": "Tunesien",
    // Group G
    "Belgium": "Belgien",
    "Egypt": "Ägypten",
    "Iran": "Iran",
    "New Zealand": "Neuseeland",
    // Group H
    "Spain": "Spanien",
    "Cape Verde": "Kap Verde",
    "Saudi Arabia": "Saudi-Arabien",
    "Uruguay": "Uruguay",
    // Group I
    "France": "Frankreich",
    "Senegal": "Senegal",
    "Iraq": "Irak",
    "Norway": "Norwegen",
    // Group J
    "Argentina": "Argentinien",
    "Algeria": "Algerien",
    "Austria": "Österreich",
    "Jordan": "Jordanien",
    // Group K
    "Portugal": "Portugal",
    "DR Congo": "DR Kongo",
    "Uzbekistan": "Usbekistan",
    "Colombia": "Kolumbien",
    // Group L
    "England": "England",
    "Croatia": "Kroatien",
    "Ghana": "Ghana",
    "Panama": "Panama",
    // Extra
    "Wales": "Wales",
    "Poland": "Polen",
    "Serbia": "Serbien",
    "Denmark": "Dänemark",
    "Italy": "Italien",
    "Nigeria": "Nigeria",
    "Costa Rica": "Costa Rica",
    "Cameroon": "Kamerun",
    "Ukraine": "Ukraine",
    "Greece": "Griechenland",
    "Chile": "Chile",
    "Peru": "Peru",
    "Bolivia": "Bolivien",
    "Venezuela": "Venezuela",
    "Jamaica": "Jamaika",
    "Honduras": "Honduras",
    "El Salvador": "El Salvador",
    "Mali": "Mali",
    "Burkina Faso": "Burkina Faso",
    "Syria": "Syrien",
    "UAE": "VAE",
    "Oman": "Oman",
    "Bahrain": "Bahrain",
    "Kuwait": "Kuwait",
    "China": "China",
    "India": "Indien",
    "Thailand": "Thailand",
    "Vietnam": "Vietnam",
    "Indonesia": "Indonesien",
    "Philippines": "Philippinen",
    "Fiji": "Fidschi",
  },
  pt: {
    "Mexico": "México", "South Korea": "Coreia do Sul", "Czechia": "República Tcheca", "South Africa": "África do Sul",
    "Canada": "Canadá", "Bosnia & Herzegovina": "Bósnia e Herzegovina", "Qatar": "Catar", "Switzerland": "Suíça",
    "Brazil": "Brasil", "Morocco": "Marrocos", "Haiti": "Haiti", "Scotland": "Escócia",
    "USA": "EUA", "Paraguay": "Paraguai", "Australia": "Austrália", "Türkiye": "Turquia", "Turkey": "Turquia",
    "Germany": "Alemanha", "Curaçao": "Curaçao", "Curacao": "Curaçao", "Ivory Coast": "Costa do Marfim", "Ecuador": "Equador",
    "Netherlands": "Países Baixos", "Japan": "Japão", "Sweden": "Suécia", "Tunisia": "Tunísia",
    "Belgium": "Bélgica", "Egypt": "Egito", "Iran": "Irã", "New Zealand": "Nova Zelândia",
    "Spain": "Espanha", "Cape Verde": "Cabo Verde", "Saudi Arabia": "Arábia Saudita", "Uruguay": "Uruguai",
    "France": "França", "Senegal": "Senegal", "Iraq": "Iraque", "Norway": "Noruega",
    "Argentina": "Argentina", "Algeria": "Argélia", "Austria": "Áustria", "Jordan": "Jordânia",
    "Portugal": "Portugal", "DR Congo": "Rep. Dem. do Congo", "Uzbekistan": "Uzbequistão", "Colombia": "Colômbia",
    "England": "Inglaterra", "Croatia": "Croácia", "Ghana": "Gana", "Panama": "Panamá",
    "Wales": "País de Gales", "Poland": "Polônia", "Serbia": "Sérvia", "Denmark": "Dinamarca",
    "Italy": "Itália", "Nigeria": "Nigéria", "Costa Rica": "Costa Rica", "Cameroon": "Camarões",
    "Ukraine": "Ucrânia", "Greece": "Grécia", "Chile": "Chile", "Peru": "Peru",
    "Bolivia": "Bolívia", "Venezuela": "Venezuela", "Jamaica": "Jamaica", "Honduras": "Honduras",
    "El Salvador": "El Salvador", "Mali": "Mali", "Burkina Faso": "Burkina Faso", "Syria": "Síria",
    "UAE": "EAU", "Oman": "Omã", "Bahrain": "Barein", "Kuwait": "Kuwait",
    "China": "China", "India": "Índia", "Thailand": "Tailândia", "Vietnam": "Vietnã",
    "Indonesia": "Indonésia", "Philippines": "Filipinas", "Fiji": "Fiji",
  },
  ru: {
    "Mexico": "Мексика", "South Korea": "Южная Корея", "Czechia": "Чехия", "South Africa": "ЮАР",
    "Canada": "Канада", "Bosnia & Herzegovina": "Босния и Герцеговина", "Qatar": "Катар", "Switzerland": "Швейцария",
    "Brazil": "Бразилия", "Morocco": "Марокко", "Haiti": "Гаити", "Scotland": "Шотландия",
    "USA": "США", "Paraguay": "Парагвай", "Australia": "Австралия", "Türkiye": "Турция", "Turkey": "Турция",
    "Germany": "Германия", "Curaçao": "Кюрасао", "Curacao": "Кюрасао", "Ivory Coast": "Кот-д'Ивуар", "Ecuador": "Эквадор",
    "Netherlands": "Нидерланды", "Japan": "Япония", "Sweden": "Швеция", "Tunisia": "Тунис",
    "Belgium": "Бельгия", "Egypt": "Египет", "Iran": "Иран", "New Zealand": "Новая Зеландия",
    "Spain": "Испания", "Cape Verde": "Кабо-Верде", "Saudi Arabia": "Саудовская Аравия", "Uruguay": "Уругвай",
    "France": "Франция", "Senegal": "Сенегал", "Iraq": "Ирак", "Norway": "Норвегия",
    "Argentina": "Аргентина", "Algeria": "Алжир", "Austria": "Австрия", "Jordan": "Иордания",
    "Portugal": "Португалия", "DR Congo": "ДР Конго", "Uzbekistan": "Узбекистан", "Colombia": "Колумбия",
    "England": "Англия", "Croatia": "Хорватия", "Ghana": "Гана", "Panama": "Панама",
    "Wales": "Уэльс", "Poland": "Польша", "Serbia": "Сербия", "Denmark": "Дания",
    "Italy": "Италия", "Nigeria": "Нигерия", "Costa Rica": "Коста-Рика", "Cameroon": "Камерун",
    "Ukraine": "Украина", "Greece": "Греция", "Chile": "Чили", "Peru": "Перу",
    "Bolivia": "Боливия", "Venezuela": "Венесуэла", "Jamaica": "Ямайка", "Honduras": "Гондурас",
    "El Salvador": "Сальвадор", "Mali": "Мали", "Burkina Faso": "Буркина-Фасо", "Syria": "Сирия",
    "UAE": "ОАЭ", "Oman": "Оман", "Bahrain": "Бахрейн", "Kuwait": "Кувейт",
    "China": "Китай", "India": "Индия", "Thailand": "Таиланд", "Vietnam": "Вьетнам",
    "Indonesia": "Индонезия", "Philippines": "Филиппины", "Fiji": "Фиджи",
  },
  ar: {
    "Mexico": "المكسيك", "South Korea": "كوريا الجنوبية", "Czechia": "التشيك", "South Africa": "جنوب أفريقيا",
    "Canada": "كندا", "Bosnia & Herzegovina": "البوسنة والهرسك", "Qatar": "قطر", "Switzerland": "سويسرا",
    "Brazil": "البرازيل", "Morocco": "المغرب", "Haiti": "هايتي", "Scotland": "اسكتلندا",
    "USA": "الولايات المتحدة", "Paraguay": "باراغواي", "Australia": "أستراليا", "Türkiye": "تركيا", "Turkey": "تركيا",
    "Germany": "ألمانيا", "Curaçao": "كوراساو", "Curacao": "كوراساو", "Ivory Coast": "ساحل العاج", "Ecuador": "الإكوادور",
    "Netherlands": "هولندا", "Japan": "اليابان", "Sweden": "السويد", "Tunisia": "تونس",
    "Belgium": "بلجيكا", "Egypt": "مصر", "Iran": "إيران", "New Zealand": "نيوزيلندا",
    "Spain": "إسبانيا", "Cape Verde": "الرأس الأخضر", "Saudi Arabia": "السعودية", "Uruguay": "أوروغواي",
    "France": "فرنسا", "Senegal": "السنغال", "Iraq": "العراق", "Norway": "النرويج",
    "Argentina": "الأرجنتين", "Algeria": "الجزائر", "Austria": "النمسا", "Jordan": "الأردن",
    "Portugal": "البرتغال", "DR Congo": "الكونغو الديمقراطية", "Uzbekistan": "أوزبكستان", "Colombia": "كولومبيا",
    "England": "إنجلترا", "Croatia": "كرواتيا", "Ghana": "غانا", "Panama": "بنما",
    "Wales": "ويلز", "Poland": "بولندا", "Serbia": "صربيا", "Denmark": "الدنمارك",
    "Italy": "إيطاليا", "Nigeria": "نيجيريا", "Costa Rica": "كوستاريكا", "Cameroon": "الكاميرون",
    "Ukraine": "أوكرانيا", "Greece": "اليونان", "Chile": "تشيلي", "Peru": "بيرو",
    "Bolivia": "بوليفيا", "Venezuela": "فنزويلا", "Jamaica": "جامايكا", "Honduras": "هندوراس",
    "El Salvador": "السلفادور", "Mali": "مالي", "Burkina Faso": "بوركينا فاسو", "Syria": "سوريا",
    "UAE": "الإمارات", "Oman": "عُمان", "Bahrain": "البحرين", "Kuwait": "الكويت",
    "China": "الصين", "India": "الهند", "Thailand": "تايلاند", "Vietnam": "فيتنام",
    "Indonesia": "إندونيسيا", "Philippines": "الفلبين", "Fiji": "فيجي",
  },
  ja: {
    "Mexico": "メキシコ", "South Korea": "韓国", "Czechia": "チェコ", "South Africa": "南アフリカ",
    "Canada": "カナダ", "Bosnia & Herzegovina": "ボスニア・ヘルツェゴビナ", "Qatar": "カタール", "Switzerland": "スイス",
    "Brazil": "ブラジル", "Morocco": "モロッコ", "Haiti": "ハイチ", "Scotland": "スコットランド",
    "USA": "アメリカ", "Paraguay": "パラグアイ", "Australia": "オーストラリア", "Türkiye": "トルコ", "Turkey": "トルコ",
    "Germany": "ドイツ", "Curaçao": "キュラソー", "Curacao": "キュラソー", "Ivory Coast": "コートジボワール", "Ecuador": "エクアドル",
    "Netherlands": "オランダ", "Japan": "日本", "Sweden": "スウェーデン", "Tunisia": "チュニジア",
    "Belgium": "ベルギー", "Egypt": "エジプト", "Iran": "イラン", "New Zealand": "ニュージーランド",
    "Spain": "スペイン", "Cape Verde": "カーボベルデ", "Saudi Arabia": "サウジアラビア", "Uruguay": "ウルグアイ",
    "France": "フランス", "Senegal": "セネガル", "Iraq": "イラク", "Norway": "ノルウェー",
    "Argentina": "アルゼンチン", "Algeria": "アルジェリア", "Austria": "オーストリア", "Jordan": "ヨルダン",
    "Portugal": "ポルトガル", "DR Congo": "コンゴ民主共和国", "Uzbekistan": "ウズベキスタン", "Colombia": "コロンビア",
    "England": "イングランド", "Croatia": "クロアチア", "Ghana": "ガーナ", "Panama": "パナマ",
    "Wales": "ウェールズ", "Poland": "ポーランド", "Serbia": "セルビア", "Denmark": "デンマーク",
    "Italy": "イタリア", "Nigeria": "ナイジェリア", "Costa Rica": "コスタリカ", "Cameroon": "カメルーン",
    "Ukraine": "ウクライナ", "Greece": "ギリシャ", "Chile": "チリ", "Peru": "ペルー",
    "Bolivia": "ボリビア", "Venezuela": "ベネズエラ", "Jamaica": "ジャマイカ", "Honduras": "ホンジュラス",
    "El Salvador": "エルサルバドル", "Mali": "マリ", "Burkina Faso": "ブルキナファソ", "Syria": "シリア",
    "UAE": "アラブ首長国連邦", "Oman": "オマーン", "Bahrain": "バーレーン", "Kuwait": "クウェート",
    "China": "中国", "India": "インド", "Thailand": "タイ", "Vietnam": "ベトナム",
    "Indonesia": "インドネシア", "Philippines": "フィリピン", "Fiji": "フィジー",
  },
  ko: {
    "Mexico": "멕시코", "South Korea": "대한민국", "Czechia": "체코", "South Africa": "남아프리카",
    "Canada": "캐나다", "Bosnia & Herzegovina": "보스니아 헤르체고비나", "Qatar": "카타르", "Switzerland": "스위스",
    "Brazil": "브라질", "Morocco": "모로코", "Haiti": "아이티", "Scotland": "스코틀랜드",
    "USA": "미국", "Paraguay": "파라과이", "Australia": "호주", "Türkiye": "터키", "Turkey": "터키",
    "Germany": "독일", "Curaçao": "퀴라소", "Curacao": "퀴라소", "Ivory Coast": "코트디부아르", "Ecuador": "에콰도르",
    "Netherlands": "네덜란드", "Japan": "일본", "Sweden": "스웨덴", "Tunisia": "튀니지",
    "Belgium": "벨기에", "Egypt": "이집트", "Iran": "이란", "New Zealand": "뉴질랜드",
    "Spain": "스페인", "Cape Verde": "카보베르데", "Saudi Arabia": "사우디아라비아", "Uruguay": "우루과이",
    "France": "프랑스", "Senegal": "세네갈", "Iraq": "이라크", "Norway": "노르웨이",
    "Argentina": "아르헨티나", "Algeria": "알제리", "Austria": "오스트리아", "Jordan": "요르단",
    "Portugal": "포르투갈", "DR Congo": "콩고 민주 공화국", "Uzbekistan": "우즈베키스탄", "Colombia": "콜롬비아",
    "England": "잉글랜드", "Croatia": "크로아티아", "Ghana": "가나", "Panama": "파나마",
    "Wales": "웨일스", "Poland": "폴란드", "Serbia": "세르비아", "Denmark": "덴마크",
    "Italy": "이탈리아", "Nigeria": "나이지리아", "Costa Rica": "코스타리카", "Cameroon": "카메룬",
    "Ukraine": "우크라이나", "Greece": "그리스", "Chile": "칠레", "Peru": "페루",
    "Bolivia": "볼리비아", "Venezuela": "베네수엘라", "Jamaica": "자메이카", "Honduras": "온두라스",
    "El Salvador": "엘살바도르", "Mali": "말리", "Burkina Faso": "부르키나파소", "Syria": "시리아",
    "UAE": "아랍에미리트", "Oman": "오만", "Bahrain": "바레인", "Kuwait": "쿠웨이트",
    "China": "중국", "India": "인도", "Thailand": "태국", "Vietnam": "베트남",
    "Indonesia": "인도네시아", "Philippines": "필리핀", "Fiji": "피지",
  },
  vi: {
    "Mexico": "México", "South Korea": "Hàn Quốc", "Czechia": "Séc", "South Africa": "Nam Phi",
    "Canada": "Canada", "Bosnia & Herzegovina": "Bosnia và Herzegovina", "Qatar": "Qatar", "Switzerland": "Thụy Sĩ",
    "Brazil": "Brazil", "Morocco": "Maroc", "Haiti": "Haiti", "Scotland": "Scotland",
    "USA": "Mỹ", "Paraguay": "Paraguay", "Australia": "Úc", "Türkiye": "Thổ Nhĩ Kỳ", "Turkey": "Thổ Nhĩ Kỳ",
    "Germany": "Đức", "Curaçao": "Curaçao", "Curacao": "Curaçao", "Ivory Coast": "Bờ Biển Ngà", "Ecuador": "Ecuador",
    "Netherlands": "Hà Lan", "Japan": "Nhật Bản", "Sweden": "Thụy Điển", "Tunisia": "Tunisia",
    "Belgium": "Bỉ", "Egypt": "Ai Cập", "Iran": "Iran", "New Zealand": "New Zealand",
    "Spain": "Tây Ban Nha", "Cape Verde": "Cabo Verde", "Saudi Arabia": "Ả Rập Xê Út", "Uruguay": "Uruguay",
    "France": "Pháp", "Senegal": "Senegal", "Iraq": "Iraq", "Norway": "Na Uy",
    "Argentina": "Argentina", "Algeria": "Algeria", "Austria": "Áo", "Jordan": "Jordan",
    "Portugal": "Bồ Đào Nha", "DR Congo": "Congo (CHDC)", "Uzbekistan": "Uzbekistan", "Colombia": "Colombia",
    "England": "Anh", "Croatia": "Croatia", "Ghana": "Ghana", "Panama": "Panama",
    "Wales": "Wales", "Poland": "Ba Lan", "Serbia": "Serbia", "Denmark": "Đan Mạch",
    "Italy": "Ý", "Nigeria": "Nigeria", "Costa Rica": "Costa Rica", "Cameroon": "Cameroon",
    "Ukraine": "Ukraine", "Greece": "Hy Lạp", "Chile": "Chile", "Peru": "Peru",
    "Bolivia": "Bolivia", "Venezuela": "Venezuela", "Jamaica": "Jamaica", "Honduras": "Honduras",
    "El Salvador": "El Salvador", "Mali": "Mali", "Burkina Faso": "Burkina Faso", "Syria": "Syria",
    "UAE": "UAE", "Oman": "Oman", "Bahrain": "Bahrain", "Kuwait": "Kuwait",
    "China": "Trung Quốc", "India": "Ấn Độ", "Thailand": "Thái Lan", "Vietnam": "Việt Nam",
    "Indonesia": "Indonesia", "Philippines": "Philippines", "Fiji": "Fiji",
  },
  id: {
    "Mexico": "Meksiko", "South Korea": "Korea Selatan", "Czechia": "Ceko", "South Africa": "Afrika Selatan",
    "Canada": "Kanada", "Bosnia & Herzegovina": "Bosnia dan Herzegovina", "Qatar": "Qatar", "Switzerland": "Swiss",
    "Brazil": "Brasil", "Morocco": "Maroko", "Haiti": "Haiti", "Scotland": "Skotlandia",
    "USA": "Amerika Serikat", "Paraguay": "Paraguay", "Australia": "Australia", "Türkiye": "Turki", "Turkey": "Turki",
    "Germany": "Jerman", "Curaçao": "Curaçao", "Curacao": "Curaçao", "Ivory Coast": "Pantai Gading", "Ecuador": "Ekuador",
    "Netherlands": "Belanda", "Japan": "Jepang", "Sweden": "Swedia", "Tunisia": "Tunisia",
    "Belgium": "Belgia", "Egypt": "Mesir", "Iran": "Iran", "New Zealand": "Selandia Baru",
    "Spain": "Spanyol", "Cape Verde": "Tanjung Verde", "Saudi Arabia": "Arab Saudi", "Uruguay": "Uruguay",
    "France": "Prancis", "Senegal": "Senegal", "Iraq": "Irak", "Norway": "Norwegia",
    "Argentina": "Argentina", "Algeria": "Aljazair", "Austria": "Austria", "Jordan": "Yordania",
    "Portugal": "Portugal", "DR Congo": "Kongo (RDK)", "Uzbekistan": "Uzbekistan", "Colombia": "Kolombia",
    "England": "Inggris", "Croatia": "Kroasia", "Ghana": "Ghana", "Panama": "Panama",
    "Wales": "Wales", "Poland": "Polandia", "Serbia": "Serbia", "Denmark": "Denmark",
    "Italy": "Italia", "Nigeria": "Nigeria", "Costa Rica": "Kosta Rika", "Cameroon": "Kamerun",
    "Ukraine": "Ukraina", "Greece": "Yunani", "Chile": "Chile", "Peru": "Peru",
    "Bolivia": "Bolivia", "Venezuela": "Venezuela", "Jamaica": "Jamaika", "Honduras": "Honduras",
    "El Salvador": "El Salvador", "Mali": "Mali", "Burkina Faso": "Burkina Faso", "Syria": "Suriah",
    "UAE": "UEA", "Oman": "Oman", "Bahrain": "Bahrain", "Kuwait": "Kuwait",
    "China": "Tiongkok", "India": "India", "Thailand": "Thailand", "Vietnam": "Vietnam",
    "Indonesia": "Indonesia", "Philippines": "Filipina", "Fiji": "Fiji",
  },
};

/** Returns the localized display name for a team. Falls back to English. */
export function getTeamDisplayName(teamName: string, locale: string): string {
  return TEAM_NAMES[locale]?.[teamName] ?? teamName;
}

// FlagCDN only supports these widths — anything else returns 404
const VALID_WIDTHS = [20, 40, 80, 160, 320, 640];

function snapWidth(size: number): number {
  return VALID_WIDTHS.reduce((prev, cur) =>
    Math.abs(cur - size) < Math.abs(prev - size) ? cur : prev
  );
}

export function getFlagUrl(teamName: string, size: number = 80): string {
  const code = TEAM_FLAG_CODES[teamName];
  if (!code) return null as unknown as string; // TBD teams handled separately
  return `https://flagcdn.com/w${snapWidth(size)}/${code}.png`;
}

export function getFlagCode(teamName: string): string {
  return TEAM_FLAG_CODES[teamName] ?? "";
}

/** Returns true if team is a placeholder (e.g. "1A", "W M73", "3rd ABCD") */
export function isTBD(teamName: string): boolean {
  if (!teamName) return true;
  return /^[123WL]/.test(teamName) && (
    /^\d[A-L]$/.test(teamName) ||       // "1A", "2B"
    /^[WL]\s+M\d+/.test(teamName) ||    // "W M73", "L M101"
    /^3rd/.test(teamName)               // "3rd ABCD"
  );
}
